#!/bin/bash -l

set -e

mode=$1
api=$2
rspec_options=$3

if [ $# -lt 2 ] || ([ "$mode" != "online" ] && [ "$mode" != "offline" ]); then
  echo "Usage:"
  echo "  ./buildpack-build online|offline api_url [rspec options]"
  exit 1
fi

if [[ -z "$rspec_options" ]]
then
  rspec_options=cf_spec
fi

if [ "$mode" == "online" ]; then
  export VAGRANT_CWD="$HOME/workspace/bosh-lite"
else
  export VAGRANT_CWD="$HOME/workspace/bosh-lite-2nd-instance"
fi

$VAGRANT_CWD/scripts/add-route

language=$(echo $(basename `git config --get remote.origin.url`) | rev | cut -d- -f1 | rev | cut -d. -f1)

echo -e "\n******* Packaging $mode buildpack for $language"

echo -e "\n******* Fetching CF CLI details"
which cf
cf --version

echo -e "\n******* Building $mode package"
rm -f ${language}_buildpack*.zip
time ./bin/package $mode

echo -e "\n******* Creating buildpack on CF"
cf api $api --skip-ssl-validation
cf login -u admin -p admin -o pivotal -s integration
cf delete-buildpack ${language}-test-buildpack -f
cf create-buildpack ${language}-test-buildpack ${language}_buildpack*.zip 1 --enable

echo -e "\n******* Configuring RVM"
export PATH=/Users/pivotal/.rvm/bin:$PATH
rvm use default

echo -e "\n******* Running specs"
BUNDLE_GEMFILE=cf.Gemfile bundle --no-cache
BUNDLE_GEMFILE=cf.Gemfile BUILDPACK_MODE=$mode rspec --format documentation --pattern "{integration,unit}/*_spec.rb" $rspec_options
